### 线程池定时执行

然线程池过一段时间再执行任务，提前安排



#### 一.Timer（以前的方法）

```java
public static void scheduledExecutorTest(){
    log.debug("start--------------");
    ScheduledExecutorService scheduled = Executors.newScheduledThreadPool(2);
    scheduled.schedule(()->{
        int i = 10 / 0;
        log.debug("123");
        ThreadSleep.sleep(1);
    },1, TimeUnit.SECONDS);

    scheduled.schedule(()->{
        log.debug("456");
    },1, TimeUnit.SECONDS);

}
```

这个方法现在基本不用，因为有2个缺点

1.任务之间只能串行执行

2.第一个运行出现问题以后，后面的任务会无法执行





#### 二.scheduledExecutorService

使用

```java
public static void scheduledExecutorTest(){
    log.debug("start--------------");
    ScheduledExecutorService scheduled = Executors.newScheduledThreadPool(2);
    scheduled.schedule(()->{
        int i = 10 / 0;
        log.debug("123");
        ThreadSleep.sleep(1);
    },1, TimeUnit.SECONDS);

    scheduled.schedule(()->{
        log.debug("456");
    },1, TimeUnit.SECONDS);
}
```

他对比timer就有优势

1.并行执行

2.任务之间出现问题也相互不影响







#### 三.定时任务（循环多次执行）

```java
public static void scheduledExecutorTest2(){
    log.debug("start--------------");
    ScheduledExecutorService scheduled = Executors.newScheduledThreadPool(2);
    /**
     * 第一个参数：
     * runnable
     * 初始延时时间
     * 间隔时间
     * 时间单位
     */
    scheduled.scheduleAtFixedRate(()->{
        log.debug("123");
    },1,1,TimeUnit.SECONDS);

    /**
     * 参数与上面那个一样
     * 但是这个的区别时需要等上一个任务运行完才进行下一个任务
     */
    scheduled.scheduleWithFixedDelay(()->{
        log.debug("123");
        ThreadSleep.sleep(2);
    },1,1,TimeUnit.SECONDS);
}
```

这里演示了2个循环多次执行的方法：

scheduleAtFixedRate与scheduleWithFixedDelay，他们的区别在于

scheduleWithFixedDelay：他的间隔时间是从上一次任务的执行结束开始算的，而scheduleAtFixedRate是根据上一次任务的开始时间来算的





#### 四.线程池任务的异常处理

我们之前发现，线程池中执行的任务如果出现了异常，他不会打印到控制台，那么。我们平时开发中该如何处理任务中的异常呢？这里有两种方式

```java
public static void threadPoolException() throws ExecutionException, InterruptedException {
    // 第一种方式，手动try-catch
    ExecutorService executorService = Executors.newFixedThreadPool(2);
    executorService.execute(()->{
        try{
            log.debug("123");
            int i = 10/0;
        }catch (Exception e){
            e.printStackTrace();
        }
    });

    // 第二种方式，使用get，代码出现异常，get的时候会抛出，推荐使用这种方式
    Future<Object> submit = executorService.submit(() -> {
        int i = 10 / 0;
        return true;
    });
    submit.get();
}
```

第一种方式就是try-catch,第二种方式就是提交任务的时候使用submit这种方式，Callable作为参数，比起Runnable，他是可以在调用get方法的时候抛出异常的，包括之前创建线程的时候使用FutureTask时，用get也能获取到参数